type ApplicationResponse = {
    id: number,
    idPas: string,
    time3: string,
    time4: string,
    timeOver: string,
    status: string,
    catPas: string,
    datetime: string,
    fullName: string,
    mobileNumber: string,
    tpz: string,
    stationFrom: MetroStationData | undefined,
    stationTo: MetroStationData | undefined,
};